#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# app_lucky_number:
#     path: /lucky/number
#     controller: App\Controller\LuckyController::number

# config/routes.yaml
projet_list:
    path:     /projet
    controller: App\Controller\ProjetController::projet_list

projet_id:
    path:     /projet/{slug}
    controller: App\Controller\ProjetController::projet_id
